#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master

install:
  - choco install gitversion.portable -y
  - ps: gitversion /l console /output buildserver
  - ps: Update-AppveyorBuild -Version $GitVersion_FullSemVer

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(GitVersion_AssemblySemVer)
  assembly_file_version: $(GitVersion_AssemblySemFileVer)
  assembly_informational_version: $(GitVersion_InformationalVersion)
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

build:
  project: EnvRun.sln

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: '**\EnvRun.exe'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  release: EnvRun-v$(appveyor_build_version)
  provider: GitHub
  auth_token:
    secure: HYngJp8YBsLRs4xGHt/P0ry3dVuu+FqEWvEJvVv4IOD6gFpxBAsQxz4yPjiy2dKp
  artifact: EnvRun.exe             # upload EnvRun.exe to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only