#---------------------------------#
#      general configuration      #
#---------------------------------#

branches:
  only:
    - master

install:
  - choco install gitversion.portable -y
  - ps: gitversion /l console /output buildserver
  - ps: Update-AppveyorBuild -Version $GitVersion_FullSemVer

assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(GitVersion_AssemblySemVer)
  assembly_file_version: $(GitVersion_MajorMinorPatch).$(APPVEYOR_BUILD_NUMBER)
  assembly_informational_version: $(GitVersion_InformationalVersion)
  
#---------------------------------#
#    environment configuration    #
#---------------------------------#

image:
- Visual Studio 2017

#---------------------------------#
#       build configuration       #
#---------------------------------#

platform:
  - Any CPU

configuration:
  - Release

build:
  project: src\EnvRun.sln

after_build:
  - ps: cd src/EnvRun/bin/Release ; 7z.exe a EnvRun-v$env:GitVersion_MajorMinorPatch.zip EnvRun.exe

#---------------------------------#
#      packaging artifacts        #
#---------------------------------#

artifacts:
  - path: 'src\EnvRun\bin\Release\EnvRun-v$(GitVersion_MajorMinorPatch).zip'

#---------------------------------#
#     deployment configuration    #
#---------------------------------#
deploy:
  tag: $(GitVersion_MajorMinorPatch)
  release: Product Release of v$(GitVersion_MajorMinorPatch)
  provider: GitHub
  auth_token:
    secure: HYngJp8YBsLRs4xGHt/P0ry3dVuu+FqEWvEJvVv4IOD6gFpxBAsQxz4yPjiy2dKp
  artifact: src\EnvRun\bin\Release\EnvRun-v$(GitVersion_MajorMinorPatch).zip
  draft: false
  prerelease: false
  force_update: true
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only
